# Generated by Django 6.0.4 on 2026-05-11 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('task_type', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Briefed', 'Briefed'), ('In Progress', 'In Progress'), ('Submitted', 'Submitted'), ('In Review', 'In Review'), ('Approved', 'Approved'), ('Rework', 'Rework'), ('Delivered', 'Delivered')], default='Briefed', max_length=20)),
                ('deadline', models.DateField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reworks', models.PositiveIntegerField(default=0)),
                ('estimated_hours', models.PositiveIntegerField(default=4)),
                ('actual_hours', models.PositiveIntegerField(default=0)),
                ('assignee', models.ForeignKey(blank=True, help_text='The main designer/member responsible for this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('concept_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_concept', to=settings.AUTH_USER_MODEL)),
                ('content_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_content', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Who allocated the task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to=settings.AUTH_USER_MODEL)),
                ('design_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_design', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workspace.workspace')),
            ],
        ),
    ]
